services:

  techdocs-runner-builder:
    container_name: techdocs-runner-builder
    image: webgrip/techdocs-builder:latest@sha256:3c33b23bdb7188de8ff9ed55b7181db3141200c5615547944154e2eadfac9b56
    pull_policy: always

  techdocs-runner:
    container_name: techdocs-runner-techdocs
    image: webgrip/techdocs-runner:latest
    pull_policy: never
    depends_on:
      techdocs-runner-builder:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ops/docker/techdocs-runner/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./docs/techdocs:/docs
