site_name: 'TechDocs and mkdocs build'
#site_description: ''

theme:
  name: 'material'

nav:
  - Index: index.md

# https://www.mkdocs.org/user-guide/configuration
plugins:
  - techdocs-core:
      use_material_search: true
  - search:
      min-search-length: 2
      prebuild_index: true
      indexing: full
  - mermaid2:
      arguments:
        securityLevel: 'loose'
  - macros

markdown_extensions:
  - markdown_inline_mermaid
  - markdown_inline_graphviz

