name: '[Workflow] On Documentation Change'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'
      - '.github/workflows/on_docs_change.yml'
  workflow_dispatch:
    inputs:
      source-dir:
        type: string
        description: 'The directory containing the techdocs files'
        required: false
        default: 'docs/techdocs'

jobs:
  placeholder:
    name: 'Placeholder'
    runs-on: ubuntu-latest
    steps:
      - name: 'Placeholder'
        run: echo 'Placeholder'
#  update-techdocs:
#    name: 'Update TechDocs'
#    uses: webgrip/workflows/.github/workflows/update_techdocs.yml@main
#    with:
#      source-dir: ${{ github.event.inputs.source-dir || 'docs/techdocs' }}
#      cname: 'docs.devops-philosophy.com'
